---
ID: "b35a2412-7bf6-4ae5-890b-64815d9a5fab"
Parent: "985401d0-85f6-48af-b37c-e943b59c22ca"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/WorldStack/SitecoreHackathonSite/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T101018Z
