---
ID: "bcc71ecd-7f93-4503-acb8-4ec71436ad28"
Parent: "82538c44-ca02-4596-8574-a8728d29e90e"
Template: "5203732f-9512-4ade-8e02-0cb085c10454"
Path: /sitecore/content/WorldStack/SitecoreHackathonSite/Settings/Site Grouping/SitecoreHackathonSite/CORS/default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{10670D11-AD0B-4E03-9118-872819CBA6B2}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T101033Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
