---
ID: "7c5b4d81-687a-48f7-8ea7-be35c24ef914"
Parent: "d5274bfc-2850-4dd6-a908-ebf946c25b3f"
Template: "d5274bfc-2850-4dd6-a908-ebf946c25b3f"
Path: /sitecore/templates/Project/WorldStack/HackathonPages/HomePage/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T101825Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
